# Generated by Django 5.1.2 on 2024-11-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_idinfo_id_number_alter_idinfo_encrypted_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idinfo',
            name='id_number',
        ),
        migrations.AddField(
            model_name='idinfo',
            name='mobile_number',
            field=models.CharField(default=111, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idinfo',
            name='vaild_till',
            field=models.CharField(default=0.0004714757190004715, max_length=10),
            preserve_default=False,
        ),
    ]
