# Generated by Django 5.1.2 on 2024-11-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_remove_idinfo_id_number_idinfo_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idinfo',
            name='vaild_till',
        ),
        migrations.AddField(
            model_name='idinfo',
            name='valid_till',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
